spring.data.mongodb.uri=mongodb+srv://root:root@cluster0.yewc588.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=AppIntakePortal


#17bd69c2b0cc3dc74ae16052a8b82f3cd0b975d

#d6d4cacc6726a1d4cc1d
